{{- if and .Values.services.enabled (gt (len .Values.services.definitions) 0) }}
{{- range .Values.services.definitions }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name  }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- if .labels }}
    {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value  }}
    {{- end }}
    {{- end }}
  annotations:
    {{- if .annotations }}
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value  }}
    {{- end }}
    {{- end }}
spec:
  type: {{ .type | default "ClusterIP"  }}
  selector:
    {{- range $key, $value := .selector }}
    {{ $key }}: {{ $value  }}
    {{- end }}
  ports:
    {{- range .ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if .protocol }}
      protocol: {{ .protocol | default "TCP"  }}
      {{- end }}
      {{- if .name }}
      name: {{ .name  }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}
