apiVersion: v2
name: teslamate
description: A Helm chart for deploying TeslaMate with Longhorn
type: application
version: 0.3.0
appVersion: "1.0"
keywords:
  - teslamate
  - tesla
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Tesla_Motors.svg/793px-Tesla_Motors.svg.png