replicaCount: 1

image:
  repository: teslamate/teslamate
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4000

env:
  DATABASE_HOST: "database"
  MQTT_HOST: "mosquitto"

secrets:
  ENCRYPTION_KEY: "your-strong-encryption-key" # Replace with a secure key
  DATABASE_USER: "teslamate"
  DATABASE_PASS: "your-secure-database-password" # Replace with a secure password
  DATABASE_NAME: "teslamate"

persistence:
  enabled: true
  import:
    mountPath: /opt/app/import
    existingClaim: ""
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 1Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

ingressRoute:
  enabled: false
  metadata:
    name: ""
    namespace: ""
  annotations: {}
  spec:
    entrypoints:
      - websecure
    routes:
      - match: Host(`teslamate.example.com`)
        kind: Rule
        services:
          - name: teslamate
            port: 4000
        middlewares: []
    tls:
      enabled: false
      secretName: ""


nodeSelector: {}
tolerations: []
affinity: {}
