replicaCount: 1

image:
  repository: teslamate/teslamate
  tag: v1.25.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4000

ingressRoute:
  enabled: true
  host: teslamate.example.com
  tls:
    enabled: true
    secretName: teslamate-tls
  annotations: {}
  middlewares: []

resources:
  limits:
    memory: "1Gi"
    cpu: "500m"
  requests:
    memory: "512Mi"
    cpu: "250m"

persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 10Gi
  dataPath: /data

# Non-sensitive environment variables managed via ConfigMap
config:
  environment:
    DATABASE_NAME: teslamate
    DATABASE_HOST: postgres
    # Add other non-sensitive env variables here

# Sensitive environment variables managed via Secrets
envSecrets:
  db:
    username: teslamate
    password: secretpassword

network:
  ports:
    - containerPort: 4000
      name: http
      protocol: TCP

labels: {}
