apiVersion: v2
name: guacamole
description: A Helm chart for Apache Guacamole - remote desktop gateway
type: application
version: 0.1.1
appVersion: "1.5.5"
home: https://guacamole.apache.org
sources:
  - https://github.com/apache/guacamole-server
keywords:
  - guacamole
  - remote-desktop
  - vnc
  - rdp
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Networking
