apiVersion: v2
name: custom-error-pages
description: A Helm chart for tarampampam/error-pages — a beautiful server error response pages
type: application
version: 0.3.0
appVersion: "2.28.0"
home: https://github.com/tarampampam/error-pages
sources:
  - https://github.com/tarampampam/error-pages
keywords:
  - error-pages
  - custom-errors
  - nginx
  - traefik
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Networking