apiVersion: v2
name: jackett
description: A Helm chart for Jackett - torrent indexer proxy
type: application
version: 0.1.0
appVersion: "0.22.1122"
home: https://github.com/Jackett/Jackett
sources:
  - https://github.com/Jackett/Jackett
keywords:
  - jackett
  - indexer
  - torrent
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Media
