image:
  repository: linuxserver/heimdall
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

env:
  TZ: "UTC"
  PUID: "1000"
  PGID: "1000"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: heimdall.local
      paths:
        - /
  tls: []
  ingressClassName: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
