apiVersion: v2
name: couchpotato
description: A Helm chart for CouchPotato - movie download manager
type: application
version: 0.1.1
appVersion: "3.0.1"
home: https://couchpota.to
sources:
  - https://github.com/CouchPotato/CouchPotatoServer
keywords:
  - couchpotato
  - movies
  - automation
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Media
