{{- if .Values.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "drone-ci.fullname" . }}-config
  labels:
    {{- include "drone-ci.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.config.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
{{- end }}
