apiVersion: v2
name: ombi
description: A Helm chart for Ombi - media request manager
type: application
version: 0.1.0
appVersion: "4.44.1"
home: https://ombi.io
sources:
  - https://github.com/Ombi-app/Ombi
keywords:
  - ombi
  - requests
  - plex
  - media
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Media
