apiVersion: v2
name: minecraft-server
description: A Helm chart for Minecraft Java Server
type: application
version: 0.1.0
appVersion: "latest"
home: https://www.minecraft.net
sources:
  - https://github.com/itzg/docker-minecraft-server
keywords:
  - minecraft
  - java
  - gaming
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Gaming
