image:
  repository: gotify/server
  tag: "2.1.5"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: gotify.local
      paths:
        - /
  tls: []
  ingressClassName: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

gotify:
  server:
    listenaddr: "0.0.0.0"
    port: 80
    ssl:
      enabled: false
      redirecttohttps: false
      certfile: ""
      keyfile: ""
  database:
    dialect: sqlite3
    connection: "data/gotify.db"
  defaultuser:
    name: admin
    pass: admin
  passstrength: 10
  uploadedimagesdir: "data/images"
