apiVersion: v1
kind: Service
metadata:
  name: spotify-client
  labels:
    {{ include "spotify.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webService.type | quote }}
  ports:
    - name: http
      port: {{ .Values.webService.port }}
      targetPort: {{ .Values.webService.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: "{{ include "spotify.name" . }}-client"