apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spotify.fullname" $ }}-client
  labels:
    {{ include "spotify.labels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "spotify.name" $ }}-client"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "spotify.name" $ }}-client"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - name: spotify-client
          image: "{{ .Values.webImage.repository }}:{{ .Values.webImage.tag }}"
          imagePullPolicy: "{{ .Values.webImage.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.webService.port }}
          env:
            - name: API_ENDPOINT
              value: "{{ .Values.clientEnv.API_ENDPOINT }}"
            - name: LOG_LEVEL
              value: "{{ .Values.clientEnv.LOG_LEVEL }}"