apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spotify.fullname" $ }}-server
  labels:
    {{ include "spotify.labels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "spotify.name" $ }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "spotify.name" $ }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - name: spotify
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          env:
            - name: APP_URL
              value: "{{ .Values.env.APP_URL }}"
            - name: SPOTIFY_PUBLIC
              value: "{{ .Values.env.SPOTIFY_PUBLIC }}"
            - name: SPOTIFY_SECRET
              value: "{{ .Values.env.SPOTIFY_SECRET }}"
            - name: MONGO_ENDPOINT
              value: "{{ .Values.env.MONGO_ENDPOINT }}"
            - name: LOG_LEVEL
              value: "{{ .Values.env.LOG_LEVEL }}"
            - name: CORS
              value: "{{ .Values.env.CORS }}"

