apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spotify.fullname" . }}
  labels:
    {{ include "spotify.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "spotify.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "spotify.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: spotify-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "spotify.fullname" . }}-config
                  key: API_ENDPOINT
            - name: SPOTIFY_PUBLIC
              valueFrom:
                configMapKeyRef:
                  name: {{ include "spotify.fullname" . }}-config
                  key: SPOTIFY_PUBLIC
            - name: SPOTIFY_SECRET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "spotify.fullname" . }}-config
                  key: SPOTIFY_SECRET
