apiVersion: v1
kind: Service
metadata:
  name: {{ include "spotify.fullname" . }}-service
  labels:
    {{- include "spotify.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "spotify.selectorLabels" . | nindent 4 }}
