apiVersion: v1
kind: Service
metadata:
  name: spotify
  labels:
    {{ include "spotify.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
  selector:
    app.kubernetes.io/name: "{{ include "spotify.name" . }}"
