apiVersion: v1
kind: Service
metadata:
  name: {{ include "spotify.fullname" . }}-web
  labels:
    {{ include "spotify.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webService.type }}
  ports:
    - port: {{ .Values.webService.port }}
      targetPort: {{ .Values.webService.port }}
  selector:
    app.kubernetes.io/name: {{ include "spotify.name" . }}-web
