{{- if .Values.ingressRoute.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingressRoute.metadata.name | default (include "glances.fullname" .) }}
  namespace: {{ .Values.ingressRoute.metadata.namespace | default .Release.Namespace }}
  labels:
    {{- include "glances.labels" . | nindent 4 }}
  {{- with .Values.ingressRoute.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingressRoute.spec.entrypoints }}
  entryPoints:
    {{- range .Values.ingressRoute.spec.entrypoints }}
    - {{ . }}
    {{- end }}
  {{- end }}
  routes:
    {{- if .Values.ingressRoute.spec.routes }}
    {{- toYaml .Values.ingressRoute.spec.routes | nindent 4 }}
    {{- else }}
    - match: Host(`{{ include "glances.fullname" . }}.local`)
      kind: Rule
      services:
        - name: {{ include "glances.fullname" . }}
          port: {{ .Values.service.port }}
    {{- end }}
  {{- if .Values.ingressRoute.spec.tls.enabled }}
  tls:
    {{- if .Values.ingressRoute.spec.tls.secretName }}
    secretName: {{ .Values.ingressRoute.spec.tls.secretName }}
    {{- end }}
  {{- end }}
{{- end }}
