{{- include "common.service" . -}}kind: Service
metadata:
  name: {{ include "glances.fullname" . }}
  labels:
    {{- include "glances.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: {{ .Values.app.service.protocol }}
      name: http
  selector:
    {{- include "glances.selectorLabels" . | nindent 4 }}
