apiVersion: v2
name: wireshark
description: A Helm chart for Wireshark - network protocol analyzer
type: application
version: 0.1.1
appVersion: "4.4.2"
home: https://www.wireshark.org
sources:
  - https://github.com/wireshark/wireshark
keywords:
  - wireshark
  - network
  - analysis
  - packets
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Networking
