apiVersion: v2
name: youtubedl-material
description: A Helm chart for YoutubeDL-Material - YouTube downloader
type: application
version: 0.1.0
appVersion: "4.3"
home: https://github.com/Tzahi12345/YoutubeDL-Material
sources:
  - https://github.com/Tzahi12345/YoutubeDL-Material
keywords:
  - youtube
  - downloader
  - media
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Media
