apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gotify.fullname" . }}
data:
  config.yml: |
    server:
      listenaddr: "{{ .Values.gotify.server.listenaddr }}"
      port: {{ .Values.gotify.server.port }}
      {{- if .Values.gotify.server.ssl.enabled }}
      ssl:
        enabled: true
        redirecttohttps: {{ .Values.gotify.server.ssl.redirecttohttps | default false }}
        certfile: "{{ .Values.gotify.server.ssl.certfile | default "" }}"
        keyfile: "{{ .Values.gotify.server.ssl.keyfile | default "" }}"
      {{- end }}
    database:
      dialect: "{{ .Values.gotify.database.dialect }}"
      connection: "{{ .Values.gotify.database.connection }}"
    defaultuser:
      name: "{{ .Values.gotify.defaultuser.name }}"
      pass: "{{ .Values.gotify.defaultuser.pass }}"
    passstrength: {{ .Values.gotify.passstrength }}
    uploadedimagesdir: "{{ .Values.gotify.uploadedimagesdir }}"
