apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gotify.fullname" . }}
  labels:
    {{- include "gotify.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gotify.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gotify.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yml
              subPath: config.yml
            - name: data
              mountPath: /app/data
          env:
            - name: GODEBUG
              value: "netdns=go"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "gotify.fullname" . }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "gotify.fullname" . }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
