apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teslamate.fullname" . }}
  labels:
    {{- include "teslamate.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "teslamate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "teslamate.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: teslamate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.network.ports }}
            - containerPort: {{ .containerPort }}
              name: {{ .name }}
              protocol: {{ .protocol }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "teslamate.fullname" . }}-config
            - secretRef:
                name: teslamate-db-secret
          volumeMounts:
            - name: teslamate-data
              mountPath: {{ .Values.persistence.dataPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: teslamate-data
          persistentVolumeClaim:
            claimName: {{ include "teslamate.fullname" . }}-pvc
      restartPolicy: Always
      # Define additional specifications like networks if needed
