{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ if .Values.ingressRoute.metadata.name }}
          {{ .Values.ingressRoute.metadata.name }}
        {{ else }}
          {{ include "teslamate.fullname" . }}
        {{ end }}
  namespace:  {{ if .Values.ingressRoute.metadata.namespace }}
                {{ .Values.ingressRoute.metadata.namespace }}
              {{ else }}
                {{ .Release.Namespace }}
              {{ end }}
  {{- if .Values.ingressRoute.annotations }}
  annotations:
    {{- toYaml .Values.ingressRoute.annotations | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- range .Values.ingressRoute.spec.entrypoints }}
    - {{ . }}
    {{- end }}
  routes:
    {{- range .Values.ingressRoute.spec.routes }}
    - match: {{ .match }}
      kind: {{ .kind }}
      services:
        {{- range .services }}
        - name: {{ .name }}
          port: {{ .port }}
        {{- end }}
      {{- if .middlewares }}
      middlewares:
        {{- range .middlewares }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- if .Values.ingressRoute.spec.tls.enabled }}
  tls:
    secretName: {{ .Values.ingressRoute.spec.tls.secretName }}
  {{- end }}
{{- end }}
