{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teslamate.fullname" . }}-import-pvc
  labels:
    {{- include "teslamate.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.import.accessMode }}
  storageClassName: {{ .Values.persistence.import.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.import.size }}
{{- end }}
