apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teslamate.fullname" . }}-secret
  labels:
    {{- include "teslamate.labels" . | nindent 4 }}
type: Opaque
data:
  ENCRYPTION_KEY: {{ .Values.secrets.ENCRYPTION_KEY | b64enc | quote }}
  DATABASE_USER: {{ .Values.secrets.DATABASE_USER | b64enc | quote }}
  DATABASE_PASS: {{ .Values.secrets.DATABASE_PASS | b64enc | quote }}
  DATABASE_NAME: {{ .Values.secrets.DATABASE_NAME | b64enc | quote }}
