apiVersion: v2
name: komga
description: A Helm chart for Komga - comics and manga server
type: application
version: 0.1.0
appVersion: "1.14.1"
home: https://komga.org
sources:
  - https://github.com/gotson/komga
keywords:
  - komga
  - comics
  - manga
  - reader
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Media
