apiVersion: v2
name: znc
description: A Helm chart for ZNC - IRC bouncer
type: application
version: 0.1.1
appVersion: "1.9.1"
home: https://wiki.znc.in
sources:
  - https://github.com/znc/znc
keywords:
  - znc
  - irc
  - bouncer
  - chat
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Communication
