apiVersion: v2
name: bazarr
description: A Helm chart for Bazarr — automatic subtitle management for Sonarr and Radarr
type: application
version: 0.1.1
appVersion: "1.5.1"
home: https://www.bazarr.media
sources:
  - https://github.com/morpheus65535/bazarr
keywords:
  - bazarr
  - subtitles
  - media
  - automation
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Media/Automation
