apiVersion: v2
name: spotify
description: A Helm chart for a self-hosted Spotify server and client
type: application
version: 0.28.0
appVersion: "1.9"
home: https://github.com/spotify
keywords:
  - spotify
  - music
  - streaming
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Media
