replicaCount: 1

image:
  repository: yooooomi/your_spotify_server
  tag: "latest"
  pullPolicy: IfNotPresent

webImage:
  repository: yooooomi/your_spotify_client
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

webService:
  type: ClusterIP
  port: 3000

customConfig:
  domain: cyphers.app
  subdomains:
    server: server
    client: web

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: "{{ .Values.customConfig.subdomains.server }}.{{ .Values.customConfig.domain }}"
      paths:
        - path: /
          pathType: Prefix
    - host: "{{ .Values.customConfig.subdomains.client }}.{{ .Values.customConfig.domain }}"
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: false
    hosts:
      - "{{ .Values.customConfig.subdomains.server }}.{{ .Values.customConfig.domain }}"
      - "{{ .Values.customConfig.subdomains.client }}.{{ .Values.customConfig.domain }}"
    secretName: your-tls-secret
environment:
  spotify:
    API_ENDPOINT: http://localhost:8080 # Ensure this is set in Spotify dashboard
    CLIENT_ENDPOINT: http://localhost:3000
    SPOTIFY_PUBLIC: __your_spotify_client_id__
    SPOTIFY_SECRET: __your_spotify_secret__
