replicaCount: 1
fullnameOverride: "spotify"
nameOverride: "spotify"

image:
  repository: yooooomi/your_spotify_server
  tag: "latest"
  pullPolicy: IfNotPresent

webImage:
  repository: yooooomi/your_spotify_client
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

webService:
  type: ClusterIP
  port: 3000

config:
  domain: xyz.app
  subdomains:
    server: server
    client: web
  apiEndpoint: "http://server.demo.app"
  mongoEndpoint: "mongodb://localhost:27017"
  clientEndpoint: "http://web.demo.app"
  spotifyPublic: "__your_spotify_client_id__"
  spotifySecret: "__your_spotify_secret__"

ingress:
  enabled: true
  annotations:
    # traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: "{{ .Values.config.subdomains.server }}.{{ .Values.config.domain }}"
      paths:
        - path: /
          pathType: Prefix
    - host: "{{ .Values.config.subdomains.client }}.{{ .Values.config.domain }}"
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: false
    hosts:
      - "{{ .Values.config.subdomains.server }}.{{ .Values.config.domain }}"
      - "{{ .Values.config.subdomains.client }}.{{ .Values.config.domain }}"
    secretName: your-tls-secret
environment:
  spotify:
    API_ENDPOINT: http://localhost:8080 # Ensure this is set in Spotify dashboard
    CLIENT_ENDPOINT: http://localhost:3000
    SPOTIFY_PUBLIC: __your_spotify_client_id__
    SPOTIFY_SECRET: __your_spotify_secret__
