replicaCount: 1
fullnameOverride: "spotify"
nameOverride: "spotify"

image:
  repository: lscr.io/linuxserver/your_spotify
  tag: "1.6.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080

env:
  APP_URL: "http://localhost:8080"
  SPOTIFY_PUBLIC: "__your_spotify_client_id__"
  SPOTIFY_SECRET: "__your_spotify_secret__"
  MONGO_ENDPOINT: "mongodb://mongo:27017/spotify"
  LOG_LEVEL: info
  CORS: "http://localhost:3000"