apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adguard-home.fullname" . }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "adguard-home.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "adguard-home.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: dns
              containerPort: {{ .Values.service.dnsPort }}
              protocol: UDP
            - name: dhcp
              containerPort: {{ .Values.service.dhcpPort }}
              protocol: UDP
            - name: dhcp-sec
              containerPort: {{ .Values.service.dhcpSecPort }}
              protocol: TCP
            - name: tls
              containerPort: {{ .Values.service.tlsPort }}
              protocol: TCP
            - name: http-alt
              containerPort: {{ .Values.service.httpAltPort }}
              protocol: TCP
            - name: https-alt
              containerPort: {{ .Values.service.httpsAltPort }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.dataPath }}
            - name: config
              mountPath: {{ .Values.persistence.configPath }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "adguard-home.dataPvcName" . }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "adguard-home.configPvcName" . }}
