apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard-home.dataPvcName" . }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | default "standard" }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard-home.configPvcName" . }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | default "standard" }}
