apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  type: LoadBalancer  # Keep it as ClusterIP
  externalIPs:
    {{- range .Values.service.externalIPs }}
    - {{ . | quote }}
    {{- end }}
  externalTrafficPolicy: Local
  ports:
    - port: 53
      targetPort: {{ .Values.service.dnsPort | default 53 }}
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: {{ .Values.service.dnsPort | default 53 }}
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target.port | default .Values.service.port }}
      name: http
    - port: {{ .Values.service.dhcpPort }}
      targetPort: {{ .Values.service.target.dhcpPort | default .Values.service.dhcpPort }}
      name: dhcp
    - port: {{ .Values.service.dhcpSecPort }}
      targetPort: {{ .Values.service.target.dhcpSecPort | default .Values.service.dhcpSecPort }}
      name: dhcp-sec
    - port: {{ .Values.service.tlsPort }}
      targetPort: {{ .Values.service.target.tlsPort | default .Values.service.tlsPort }}
      name: tls
    - port: {{ .Values.service.httpAltPort }}
      targetPort: {{ .Values.service.target.httpAltPort | default .Values.service.httpAltPort }}
      name: http-alt
    - port: {{ .Values.service.httpsAltPort }}
      targetPort: {{ .Values.service.target.httpsAltPort | default .Values.service.httpsAltPort }}
      name: https-alt
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}
