apiVersion: v2
name: it-tools
description: A Helm chart for IT-Tools — a collection of handy online developer tools
type: application
version: 0.5.0
appVersion: "2024.5.13-a0bc346"
home: https://it-tools.tech
sources:
  - https://github.com/CorentinTh/it-tools
keywords:
  - it-tools
  - developer-tools
  - utilities
  - self-hosted
icon: https://raw.githubusercontent.com/CorentinTh/it-tools/main/public/favicon.png
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Utilities
