apiVersion: v2
name: minio
description: A Helm chart for MinIO - S3-compatible object storage
type: application
version: 0.1.1
appVersion: "latest"
home: https://min.io
sources:
  - https://github.com/minio/minio
keywords:
  - minio
  - s3
  - storage
  - object-storage
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Storage
