apiVersion: v2
name: deluge
description: A Helm chart for Deluge - lightweight BitTorrent client
type: application
version: 0.1.1
appVersion: "2.1.1"
home: https://deluge-torrent.org
sources:
  - https://github.com/deluge-torrent/deluge
keywords:
  - deluge
  - torrent
  - bittorrent
  - downloader
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Downloads
