apiVersion: v2
name: duplicati
description: A Helm chart for Duplicati - free backup client
type: application
version: 0.1.1
appVersion: "2.1.0.2"
home: https://www.duplicati.com
sources:
  - https://github.com/duplicati/duplicati
keywords:
  - duplicati
  - backup
  - encryption
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Backup
