apiVersion: v2
name: openhab
description: A Helm chart for openHAB - home automation bus
type: application
version: 0.1.0
appVersion: "4.3.0"
home: https://www.openhab.org
sources:
  - https://github.com/openhab/openhab-core
keywords:
  - openhab
  - home-automation
  - iot
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Automation
