apiVersion: v2
name: glances
description: A Helm chart for Glances — a cross-platform system monitoring tool
type: application
version: 0.3.0
appVersion: "4.2.1"
home: https://nicolargo.github.io/glances/
sources:
  - https://github.com/nicolargo/glances
keywords:
  - glances
  - monitoring
  - system
  - performance
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Monitoring
