apiVersion: v2
name: cloudbeaver
description: A Helm chart for CloudBeaver — a cloud database manager with web UI
type: application
version: 0.2.0
appVersion: "24.3.4"
home: https://dbeaver.com/docs/cloudbeaver/
sources:
  - https://github.com/dbeaver/cloudbeaver
keywords:
  - cloudbeaver
  - database
  - dbeaver
  - sql
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Database
