# Default values for CloudBeaver Helm Chart

# -------------------------------------
# General Settings
# -------------------------------------

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

# -------------------------------------
# Image Settings
# -------------------------------------

image:
  repository: dbeaver/cloudbeaver
  tag: "23.1.3"  # Use a specific version for stability
  pullPolicy: IfNotPresent
imagePullSecrets: []

# -------------------------------------
# Pod Settings
# -------------------------------------

podAnnotations: {}
podLabels: {}
additionalLabels: {}  # Renamed 'labels' to 'additionalLabels' for clarity

podSecurityContext: {}
securityContext: {}

serviceAccount:
  create: false
  name: ""
  annotations: {}

nodeSelector: {}
tolerations: []
affinity: {}

# -------------------------------------
# Container Settings
# -------------------------------------

containerPorts:
  - name: http
    containerPort: 8978
    protocol: TCP

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# -------------------------------------
# Volume Settings
# -------------------------------------

volumes: []
volumeMounts: []
extraVolumeMounts: []

persistentVolumeClaims:
  enabled: true
  claims:
    - name: cloudbeaver-data
      create: true  # Added to specify if PVC should be created
      accessModes:
        - ReadWriteOnce
      storageClassName: ""  # Specify storage class if needed
      resources:
        requests:
          storage: 1Gi
      mountPath: /opt/cloudbeaver/workspace  # Mount path in the container
      subPath: ""  # Optional subPath within the volume
      readOnly: false  # Specify if the volume should be read-only

# -------------------------------------
# Ingress Settings
# -------------------------------------

ingress:
  enabled: false
  annotations: {}
  className: ""  # Specify the ingress class name if needed
  hosts:
    - host: cloudbeaver.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cloudbeaver-tls
      hosts:
        - cloudbeaver.example.com

# -------------------------------------
# IngressRoute Settings (Traefik)
# -------------------------------------

ingressRoute:
  enabled: false  # Set to true if using Traefik's IngressRoute
  namespace: ""
  annotations: {}
  entryPoints:
    - websecure
  routes:
    - match: Host(`cloudbeaver.example.com`)
      kind: Rule
      middlewares: []
      services:
        - name: cloudbeaver
          port: 80

# -------------------------------------
# Service Settings
# -------------------------------------

service:
  type: ClusterIP
  port: 80
  targetPort: http  # Use port name defined in containerPorts for flexibility

# -------------------------------------
# Configuration Settings
# -------------------------------------

configmap:
  enabled: true  # Enabled to allow custom configurations
  data:
    CB_SERVER_NAME: "CloudBeaver Server"
    CB_SESSION_EXPIRE_PERIOD: "3600"
    # Add additional configurations as needed

secret:
  enabled: true
  type: Opaque
  data:
    CB_ADMIN_NAME: "admin"
    CB_ADMIN_PASSWORD: "securepassword"
    # Consider using Helm's built-in functions to handle sensitive data

# -------------------------------------
# Additional Kubernetes Services
# -------------------------------------

services:
  enabled: false
  definitions: []

# -------------------------------------
# Logging and Monitoring Settings
# -------------------------------------

logging:
  level: INFO  # Set logging level (e.g., DEBUG, INFO, WARN, ERROR)

# -------------------------------------
# Autoscaling Settings
# -------------------------------------

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# -------------------------------------
# Additional Environment Variables
# -------------------------------------

extraEnvVars: []
# Example:
# extraEnvVars:
#   - name: JAVA_OPTS
#     value: "-Xms256m -Xmx512m"

# -------------------------------------
# Additional Init Containers
# -------------------------------------

initContainers: []
# Example:
# initContainers:
#   - name: init-myservice
#     image: busybox
#     command: ['sh', '-c', 'echo Init Container']
