apiVersion: v2
name: mylar
description: A Helm chart for Mylar3 - comic book downloader
type: application
version: 0.1.0
appVersion: "0.7.6"
home: https://github.com/mylar3/mylar3
sources:
  - https://github.com/mylar3/mylar3
keywords:
  - mylar
  - comics
  - automation
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Media
