apiVersion: v2
name: tiddlywiki
description: A Helm chart for TiddlyWiki - non-linear personal notebook
type: application
version: 0.1.1
appVersion: "5.3.6"
home: https://tiddlywiki.com
sources:
  - https://github.com/TiddlyWiki/TiddlyWiki5
keywords:
  - tiddlywiki
  - wiki
  - notes
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Productivity
