apiVersion: v2
name: gitea
description: A Helm chart for Gitea - lightweight Git hosting
type: application
version: 0.1.1
appVersion: "1.22.6"
home: https://gitea.io
sources:
  - https://github.com/go-gitea/gitea
keywords:
  - gitea
  - git
  - hosting
  - development
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Development
