apiVersion: v2
name: gitlab
description: A Helm chart for GitLab CE - DevOps platform
type: application
version: 0.1.1
appVersion: "17.7.0"
home: https://about.gitlab.com
sources:
  - https://gitlab.com/gitlab-org/gitlab
keywords:
  - gitlab
  - git
  - devops
  - ci
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Development
