apiVersion: v2
name: duplicacy
description: A Helm chart for Duplicacy - cloud backup tool
type: application
version: 0.1.0
appVersion: "1.8.0"
home: https://duplicacy.com
sources:
  - https://github.com/gilbertchen/duplicacy
keywords:
  - duplicacy
  - backup
  - cloud
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Backup
