{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: {{ .Values.secret.type | default "Opaque" }}
data:
{{- if .Values.secret.data }}
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- else }}
  # No data provided for the Secret.
{{- end }}
{{- end }}
