apiVersion: v2
name: homebridge
description: A Helm chart for Homebridge - HomeKit bridge
type: application
version: 0.1.0
appVersion: "1.8.4"
home: https://homebridge.io
sources:
  - https://github.com/homebridge/homebridge
keywords:
  - homebridge
  - homekit
  - apple
  - automation
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Automation
