name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Install helm-docs
        run: |
          cd /tmp
          wget https://github.com/norwoodj/helm-docs/releases/download/v1.11.0/helm-docs_1.11.0_Linux_x86_64.tar.gz
          tar -xvf helm-docs_1.11.0_Linux_x86_64.tar.gz
          sudo mv helm-docs /usr/local/bin

      - name: Run helm-docs
        run: |
          find charts -type f -name 'Chart.yaml' | xargs dirname | xargs helm-docs --dry-run

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.8.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: charts/
          framework: kubernetes
          soft_fail: true

  validate-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate Chart Versions
        run: |
          # Check that chart versions are properly incremented
          find charts -name 'Chart.yaml' -exec grep -H "version:" {} \; | while read -r line; do
            echo "Found chart version: $line"
          done

      - name: Check Required Files
        run: |
          # Ensure all charts have required files
          for chart_dir in charts/stable/* charts/beta/*; do
            if [ -d "$chart_dir" ]; then
              echo "Checking $chart_dir"

              # Required files
              [ -f "$chart_dir/Chart.yaml" ] || { echo "Missing Chart.yaml in $chart_dir"; exit 1; }
              [ -f "$chart_dir/values.yaml" ] || { echo "Missing values.yaml in $chart_dir"; exit 1; }
              [ -d "$chart_dir/templates" ] || { echo "Missing templates/ in $chart_dir"; exit 1; }
              [ -f "$chart_dir/README.md" ] || echo "Warning: Missing README.md in $chart_dir"

              echo "✅ $chart_dir passed validation"
            fi
          done
