# name: Release Charts

# on:
#   push:
#     # Trigger when chart version tags are pushed
#     tags:
#       - '*'
#   workflow_dispatch:

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Configure Git
#         run: |
#           git config user.name "$GITHUB_ACTOR"
#           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

#       - name: Install Helm
#         uses: azure/setup-helm@v4
#         env:
#           GITHUB_TOKEN: "${{ secrets.access_token }}"
#       - name: Lint Helm charts beta
#         run: helm lint charts/beta/*
#       - name: Lint Helm charts stable
#         run: helm lint charts/stable/*
#       - name: Run chart-releaser-stable
#         uses: helm/chart-releaser-action@v1.6.0
#         with:
#           charts_dir: charts/stable/
#           skip_existing: true
#         env:
#           CR_TOKEN: "${{ secrets.access_token }}"

#       - name: Run chart-releaser-beta
#         uses: helm/chart-releaser-action@v1.6.0
#         with:
#           charts_dir: charts/beta/
#           skip_existing: true
#         env:
#           CR_TOKEN: "${{ secrets.access_token }}"

#       - name: Run chart-releaser-experimental
#         uses: helm/chart-releaser-action@v1.6.0
#         with:
#           charts_dir: charts/experimental/
#           skip_existing: true
#         env:
#           CR_TOKEN: "${{ secrets.access_token }}"
