apiVersion: v2
name: sickchill
description: A Helm chart for SickChill - TV show automation
type: application
version: 0.1.1
appVersion: "2024.3.1"
home: https://sickchill.github.io
sources:
  - https://github.com/SickChill/SickChill
keywords:
  - sickchill
  - tv
  - automation
  - self-hosted
maintainers:
  - name: HomeOpsHub
    url: https://github.com/HomeOpsHub
annotations:
  category: Media
